# Generated by Django 2.2.1 on 2019-05-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rc_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentabsentsituation',
            name='is_ask_for_leave',
            field=models.BooleanField(choices=[(True, '已请假'), (False, '未请假')], default=False, verbose_name='是否请假'),
        ),
    ]
