# Generated by Django 2.2.1 on 2019-06-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rc_app', '0002_studentabsentsituation_is_ask_for_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='absent_times',
            field=models.IntegerField(default=0, verbose_name='缺勤次数'),
        ),
    ]
