# Generated by Django 2.2.1 on 2019-06-04 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rc_app', '0004_course_course_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['class_name', 'absent_times', 'attendance_times'], 'verbose_name_plural': '学生信息'},
        ),
        migrations.AddField(
            model_name='student',
            name='attendance_times',
            field=models.IntegerField(default=0, verbose_name='出勤次数'),
        ),
    ]
