# Generated by Django 2.2.1 on 2019-06-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rc_app', '0005_auto_20190604_0957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['class_name'], 'verbose_name_plural': '学生信息'},
        ),
        migrations.AlterModelOptions(
            name='studentcourse',
            options={'ordering': ['course', 'absent_times'], 'verbose_name_plural': '学生课程对应关系'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='absent_times',
        ),
        migrations.RemoveField(
            model_name='student',
            name='attendance_times',
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='absent_times',
            field=models.IntegerField(default=0, verbose_name='缺勤次数'),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='attendance_times',
            field=models.IntegerField(default=0, verbose_name='出勤次数'),
        ),
    ]
