# Generated by Django 2.2.2 on 2019-06-07 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rc_app', '0006_auto_20190605_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentpicture',
            options={'verbose_name_plural': '学生照片'},
        ),
        migrations.AlterModelTable(
            name='studentpicture',
            table='StudentPicture',
        ),
    ]
