# Generated by Django 2.2.2 on 2019-06-11 08:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rc_app', '0007_auto_20190607_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentabsentsituation',
            name='absent_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, verbose_name='缺勤时间'),
            preserve_default=False,
        ),
    ]
