# Generated by Django 2.2.2 on 2019-06-11 12:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rc_app', '0009_auto_20190611_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentabsentsituation',
            name='absent_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='缺勤时间'),
        ),
    ]
